### ISSUE TITLE
v1 discussion

### ISSUE THREAD

**Issue by thgaskell** [sudokrew/krewcumber#1]
The purpose of this repo is so that we can drop `.feature` files into our projects and have working end-to-end tests.

What are things required to start using this to test our web apps?

- What are common features we need to test?
- What will benefit from being automated?
    - Filling out forms
    - Navigation
    - Observed values
- How do we describe these features in Gherkin? The language should avoid developer language if possible, especially referencing class ids, or using variable names that are not apparent to an enduser.

**Bad example**
```
When I enter "user@example.com" into the "input#email[type=\"text"]" field
 And I enter the "p@$5w0rd" into the "input#password[type=\"password\"]" field
 And I click the "button#login-submit" button
Then I should be on the "/dashboard" page
```

**Better example**
```
When I enter "user@example.com" into the "email" field
 And I enter the "p@$5w0rd" into the "password" field
 And I submit the form
Then I should be on the "/dashboard" page
```

Ideally, it should almost read like feature documentation. The benefit here is that a non-developer could affect tests (provided they follow an agreed upon business language).

We should be able to handle the complexities in the step definition files.

**Comment by mrbarbasa** [comment]
It'd be great to avoid selectors altogether in the Gherkin files, but in practice, it can't always be avoided.  How would we solve the issue of clicking a link that has the same text in two different places on the same page?  How would we solve complex forms that have multiple fields of the same label (such as adding multiple contacts or sites)?

**Comment by thgaskell** [comment]
I think we're going to focus on the major use cases and will address edge cases on a later iteration.

In the case of multiple elements that are similar, I think there are some ideas that may be worth exploring:

- Update the step regex to include allow for a counter of some sort
    - Example: `When I click the second "Edit" link`
- Add a step that is relative to the currently selected element
    - Example: `When I select the next "Address" input`
    - Example: `When I enter "foo" into the next "Details" input`

**Comment by thgaskell** [comment]
Thanks everyone for feedback, I've updated the [wiki with steps](https://github.com/sudokrew/krewcumber/wiki/Step-Documentation) that would like to include for the first iteration.

I'm closing this issue, but feel free to continue discussion here if there's any gaping holes in what can/cannot be tested.
